#!/usr/bin/env python3
"""
Core Module - Foundational components for CV Automation System
Exports constants, models, exceptions, and utilities
"""

from .constants import (
    SynergieColors,
    SynergieFonts,
    FontSizes,
    SynergiePageSetup,
    SynergieTableSpecs,
    PageSetup,
    TableSpecs,
    SectionNames,
    FilePatterns,
    ProcessingConfig,
    DateFormats,
    SectionPatterns,
    LanguageIndicators,
    ValidationRules,
    Paths,
    LogConfig,
    TemplateSpecs,
    SystemInfo,
    QualityThresholds,
)

from .models import (
    ProcessingStatus,
    ExtractionMethod,
    Language,
    FileFormat,
    ReviewPriority,
    CVFile,
    ExtractionResult,
    PersonalInfo,
    DateRange,
    Project,
    WorkExperience,
    Education,
    Course,
    CVData,
    ResumeData,
    ValidationError,
    ValidationResult,
    ProcessingStep,
    ProcessingResult,
    ReviewItem,
    BatchJob,
    Section,
    ParsedCV,
    SystemMetrics,
    SystemConfig,
    FileMetadata,
    LogEntry,
)

from .exceptions import (
    CVAutomationException,
    InputException,
    FileNotFoundException,
    InvalidFileFormatException,
    FileCorruptedException,
    FileTooLargeException,
    FileTooSmallException,
    ExtractionException,
    TextExtractionFailedException,
    OCRRequiredException,
    OCRFailedException,
    UnsupportedDocumentException,
    ParsingException,
    SectionNotFoundException,
    DateParsingException,
    LanguageDetectionException,
    NameExtractionException,
    ValidationException,
    MissingRequiredFieldException,
    InvalidDataException,
    LowConfidenceException,
    GenerationException,
    TemplateLoadException,
    TableCreationException,
    FormattingException,
    PDFConversionException,
    OutputException,
    FileSaveException,
    FileAlreadyExistsException,
    PermissionException,
    DatabaseException,
    RecordNotFoundException,
    DuplicateRecordException,
    ConfigurationException,
    MissingConfigException,
    InvalidConfigException,
)

from .utils import (
    generate_file_id,
    get_file_extension,
    is_cv_file,
    is_resume_file,
    get_person_name_from_path,
    ensure_directory_exists,
    clean_text,
    normalize_whitespace,
    extract_name_components,
    extract_city_from_location,
    extract_year_from_text,
    is_current_date_indicator,
    normalize_date_format,
    detect_language,
    is_valid_birth_year,
    is_valid_email,
    is_valid_phone,
    truncate_string,
    remove_special_characters,
    capitalize_name,
    format_bullet_points,
    remove_bullet_points,
    get_person_folder,
    get_resume_output_path,
    format_log_message,
    log_processing_step,
    calculate_eta,
    format_file_size,
    format_duration,
    merge_dicts,
    flatten_list,
    ProgressTracker,
    Timer,
    print_section_header,
    print_subsection_header,
    print_key_value,
    print_table_row,
    validate_file_exists,
    validate_file_readable,
    validate_directory_writable,
    debug_print_dict,
    safe_get,
)

__version__ = "1.0.0"
__all__ = [
    # Constants
    'SynergieColors', 'SynergieFonts', 'FontSizes', 'SynergiePageSetup', 'SynergieTableSpecs',
    'PageSetup', 'TableSpecs', 'SectionNames', 'FilePatterns', 'ProcessingConfig', 'DateFormats',
    'SectionPatterns', 'LanguageIndicators', 'ProcessingStatus', 'ExtractionMethod',
    'Language', 'ValidationRules', 'Paths', 'LogConfig', 'TemplateSpecs',
    'SystemInfo', 'QualityThresholds',
    
    # Models
    'FileFormat', 'ReviewPriority', 'CVFile', 'ExtractionResult', 'PersonalInfo',
    'DateRange', 'Project', 'WorkExperience', 'Education', 'Course', 'CVData',
    'ResumeData', 'ValidationError', 'ValidationResult', 'ProcessingStep',
    'ProcessingResult', 'ReviewItem', 'BatchJob', 'Section', 'ParsedCV',
    'SystemMetrics', 'SystemConfig', 'FileMetadata', 'LogEntry',
    
    # Exceptions
    'CVAutomationException', 'InputException', 'FileNotFoundException',
    'InvalidFileFormatException', 'FileCorruptedException', 'FileTooLargeException',
    'FileTooSmallException', 'ExtractionException', 'TextExtractionFailedException',
    'OCRRequiredException', 'OCRFailedException', 'UnsupportedDocumentException',
    'ParsingException', 'SectionNotFoundException', 'DateParsingException',
    'LanguageDetectionException', 'NameExtractionException', 'ValidationException',
    'MissingRequiredFieldException', 'InvalidDataException', 'LowConfidenceException',
    'GenerationException', 'TemplateLoadException', 'TableCreationException',
    'FormattingException', 'PDFConversionException', 'OutputException',
    'FileSaveException', 'FileAlreadyExistsException', 'PermissionException',
    'DatabaseException', 'RecordNotFoundException', 'DuplicateRecordException',
    'ConfigurationException', 'MissingConfigException', 'InvalidConfigException',
    
    # Utilities
    'generate_file_id', 'get_file_extension', 'is_cv_file', 'is_resume_file',
    'get_person_name_from_path', 'ensure_directory_exists', 'clean_text',
    'normalize_whitespace', 'extract_name_components', 'extract_city_from_location',
    'extract_year_from_text', 'is_current_date_indicator', 'normalize_date_format',
    'detect_language', 'is_valid_birth_year', 'is_valid_email', 'is_valid_phone',
    'truncate_string', 'remove_special_characters', 'capitalize_name',
    'format_bullet_points', 'remove_bullet_points', 'get_person_folder',
    'get_resume_output_path', 'format_log_message', 'log_processing_step',
    'calculate_eta', 'format_file_size', 'format_duration', 'merge_dicts',
    'flatten_list', 'ProgressTracker', 'Timer', 'print_section_header',
    'print_subsection_header', 'print_key_value', 'print_table_row',
    'validate_file_exists', 'validate_file_readable', 'validate_directory_writable',
    'debug_print_dict', 'safe_get',
]

